Update README.md
thisdot/tech-meetups pull request #20
Opened 2022-10-01 13:48 UTC by Asmit2952

## Adding a meetup
- [x] Suggestion is not a duplicate
- [x] Suggestion is under the proper category
- [x] Link to meetup is included 
- [x] Name of meetup is included
- [x] Name and link are spelled correctly

## Adding a category
- [x] Category is not a duplicate
- [x] Category is spelled correctly

Fixes: #19

2022-10-01 13:49 UTC, Asmit2952 commented
Hey @jdwilkin4, are these meetups enough? These were the popular ones which I have attended virtually

2022-10-02 14:35 UTC, Asmit2952 commented
Hey @tyrelchambers @jdwilkin4 can you please give a look at this PR?

2022-10-02 16:01 UTC, jdwilkin4 commented
@Asmit2952 

The staff will be back in the office on Monday and someone will review your PR then.
Thank you for your patience. 👍

2022-10-03 14:37 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2022-10-03 14:37 UTC, jdwilkin4 commented on README.md
> +- [React India](https://www.reactindia.io/) - React India is an international conference that provides a platform for developers to share and discuss their insights and experiences with React! It Pro
```suggestion
- [React India](https://www.reactindia.io/) - React India is an international conference that provides a platform for developers to share and discuss their insights and experiences with React! It provides developers from India an opportunity to meet, listen, and network with React Developers and Open Source Contributors all around the world!
```

2022-10-03 14:40 UTC, Asmit2952 commented
> Thank you for your contribution!
> 
> Please review the requested changes. Once those changes have been implemented, then we can merge your PR into main. 👍

Done @jdwilkin4

2022-10-03 14:53 UTC, jdwilkin4 approved these changes
Congrats on your first contribution to our repository. 🎉
We look forward to future contributions. 👍

2022-10-03 14:53 UTC, merged