docs: Added HackerNext to general tech
thisdot/tech-meetups pull request #23
Opened 2022-10-13 19:29 UTC by motasimmakki

## Adding a meetup
- [x] Suggestion is not a duplicate
- [x] Suggestion is under the proper category
- [x] Link to meetup is included 
- [x] Name of the meetup is included
- [x] Name and link are spelled correctly

## Adding a category
- [x] Category is not a duplicate
- x] Category is spelled correctly

2022-10-13 22:51 UTC, jdwilkin4 requested changes
Thank you for your contribution!

Please review the requested changes.
Once those changes have been implemented, then we can merge your PR into main. 👍

2022-10-13 22:51 UTC, jdwilkin4 commented on .gitignore
> +.vscode/*
Since this repo is just filled with markdown files we shouldn't need a `.gitignore`  file.
Let's remove this

2022-10-13 22:51 UTC, jdwilkin4 commented on README.md
> +- [HackerNest (Toronto, ON)](https://www.meetup.com/hackernest/) - HackerNest runs public and curated tech events that connect people and organizations in the community.
All of the lists are alphabetical order.
Please move this just after the ExchangeJS entry.

2022-10-14 16:53 UTC, motasimmakki commented
@jdwilkin4 Kindly have a look!

2022-10-14 19:21 UTC, jdwilkin4 approved these changes
Congrats on your first contribution to our repository. 🎉
We look forward to future contributions. 👍

2022-10-14 19:21 UTC, merged